### Property File for Cybench Comparator Tool ###

# reports = location of CyBench reports folder

# token = CyBench Access Token with View Permissions
### Token can be found on the CyBench site by clicking on your username ###
### Token should be a query token with access to the specific workspace that stores your benchmarks ###

# compare.default = default comparison configurations

#compare.{} = specific comparison configurations 
### {} can be any identifier of your choice ###
### Make sure to include {package} to specify which package you want these comparisons to run on ###


### Comparison Configurations ###

# method = how benchmarks will be compared
### Options {delta, mean, SD} ###

# scope = (within or between project versions)
## Options {within, between} ##
### {within} will compare all benchmarks within the benchmarked version ###
### if {between} is chosen, must specify {version} (will compare benchmarked version to the specified version) ###
    ### add {version} to specify which version to compare to ###

# trend = whether or not to compare the trend in data
## Options {none, last_5, all_values} ##
### {none} will do a basic comparison, {last_5} will compare to last 5 values, {all_values} will compare to all values within scope ###
### ex. {method: DELTA, trend: NONE, scope: BETWEEN} will perform a simple difference calculation between the recent score if the recent version and the score of the compare version ###
### ex.{method: DELTA, trend: ALL_VALUES, scope: BETWEEN} will compare the average change in scores of the recent version to the average change in scores of the compare version ### 

# threshold = how to specify a passing benchmark 
## Options {percent_change, greater} ##
### {greater} will check to see if new score is simply greater than the compared to score ###
### if {percent_change} is chosen, must specify {percentage} ###
    ### percentage = percentage score should be within in order to pass ###
    ### ex. 5% means the new score should be within 5% of the previous threshold ###


reports: "reports/"
token: "MY TOKEN"

compare.default:
    method: "MEAN"
    threshold: "greater"
    scope: "BETWEEN"
    version: "1.0.0"
    trend: "NONE"
    
compare.A:
    method: "DELTA"
    package: "com.my.package"
    scope: "WITHIN"
    trend: "ALL_VALUES"
    
compare.B:
    pacakge: "com.my.other.package"
    percentage: "6"
    threshold: "percent_change"
    